<?php

namespace UnicornBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * captiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class captiveRepository extends EntityRepository
{
}
