<?php

namespace UnicornBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cornFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cornFormRepository extends EntityRepository
{
}
