<?php

namespace UnicornBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * hoofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hoofRepository extends EntityRepository
{
}
