<?php

namespace UnicornBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * temperatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class temperatureRepository extends EntityRepository
{
}
