<?php

namespace UnicornBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * unicornRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unicornRepository extends EntityRepository
{
}
