UnicornBundle\Entity\hairType:
    type: entity
    table: null
    repositoryClass: UnicornBundle\Repository\hairTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            unique: true
    lifecycleCallbacks: {  }
